### ISSUE TITLE
Handle missing API key

### ISSUE THREAD

**Issue by gbprz** [concerto/concerto-weather#15]
At the moment, submitting weather content without an API key causes an error. Maybe there should be a check and some sort of message to handle the error more gracefully.

**Comment by mfrederickson** [comment]
This is resolved in #26.
![image](https://cloud.githubusercontent.com/assets/473165/23039197/3f5016f8-f439-11e6-84ed-2a186333290f.png)

If there is no api key defined, a message appears when adding content.
Validation now requires a city to be selected.
