### ISSUE TITLE
City results not clearing 

### ISSUE THREAD

**Issue by gbprz** [concerto/concerto-weather#20]
I have not run into this issue, but it seems like the container with the search results for cities is not clearing. From the mailing list:

Using the concerto vm image upgraded to 2.3.3.  Have now upgraded the weather plugin to 0.3.2.   I did have to modify /usr/share/concerto/Gemfile.lock

Closer but still not working.

If I put in "Madison", it lists 14 locations (actually 7 locations, but listed twice) and I cannot pick one.
If I put in "Madison, WI", it gives the error "Name Can't Be Blank".  I assume it's not liking the space
If I put in "53705" or any of the other zip codes for Madison, Wisconsin, it lists the city TWICE with no way to pick one.

Trying to add any of the above to a feed gives a 500 error.  I am assuming this is because it was not narrowed down to a single city, which seems impossible to do since it is duplicating the listings.

**Comment by mfrederickson** [comment]
I am unable to duplicate these issues in the current version of development.  #26 does handle clearing the previous selected city's lat/lng.  The 'name can't be blank' message was for the name of the content (not the city).
