### ISSUE TITLE
Handle submission errors

### ISSUE THREAD

**Issue by gbprz** [concerto/concerto-weather#21]
If the user does not select a city from the results list, we should show some sort of warning instead of moving forward with the submission and causing an error page to show. Behind the scenes, when a user selects a city, hidden submission fields are populated. 

This can be really misleading if the user doesn't click on a search result since they think the text field input should work on it's own for content submission (especially if only one city shows up on the results). This could also be accompanied with a message requiring the user to click on a city search result or populating the text input field with their selected result.

**Comment by mfrederickson** [comment]
This has been addressed in #26.
