### ISSUE TITLE
Searching a city with more than one word return no results

### ISSUE THREAD

**Issue by mappsys** [concerto/concerto-weather#29]
Hi, When searching for a city like Rio de Janeiro ou New York, returns no results (and no visible error msgs). If you search New instead o New York the results with a partial list (there are many cities starting with New) and New York is not listed because the limited number of lines in result set. 

It seems the error is on /concerto_weather/city.search.js returning a 500 error. 

The worker-1.log shows:

[Worker(host:concerto pid:510)] Job DynamicContent.refresh (id=100) FAILED (13 prior attempts) with NoMethodError: undefined method `[]' for nil:NilClass

In Apache error.log:

App 1528 stdout: E, [2017-02-16T19:30:38.919567 #1528] ERROR -- : **Airbrake: unexpected code (200). Body:
App 1528 stdout:

**Comment by mfrederickson** [comment]
It appears that `New+York` works, so we need to urlencode the search term.
```
F, [2017-02-17T20:50:02.689434 #60499] FATAL -- : 
URI::InvalidURIError (bad URI(is not URI?): http://api.openweathermap.org/data/2.5/find?q=New York&type=like&mode=json&appid=45168c55d3cdc3):
```

**Comment by garci66** [comment]
Missed this bug.. ( I was dealing with the same issue on my side). I just pushed a PR for ir.

**Comment by mappsys** [comment]
Hi Diego, i discovered a workaround, just use comma as a separator instead of space! Works for me!

Luciano de C. Fonseca

**Comment by garci66** [comment]
In my case, New%20York worked... but the plus was causing some issues.  Not sure which encoding is the real "correct" one...  But we would still need the encoding to avoid any form of url re-write/injection, etc...
