### ISSUE TITLE
Plugin is now showing code instead of formatted text and icons.

### ISSUE THREAD

**Issue by shieldsit** [concerto/concerto-weather#42]
This just started yesterday, I have attached a screen grab of what it's doing.  Can you tell me where to start troubleshooting?  I've tried deleting the existing weather feeds and I've updated everything but it hasn't fixed the issue.

Thanks for your time!
![concerto_error](https://user-images.githubusercontent.com/4956108/30336843-69cbdc86-97b4-11e7-8a10-e3e0f1a871fa.PNG)

**Comment by mfrederickson** [comment]
@shieldsit can you tell me what version of concerto you are using, and what version of the concerto-frontend and concerto-weather plugins?

**Comment by shieldsit** [comment]
Sure can and thanks for the fast reply!

Concerto Version: 2.3.5
Frontend Version: 0.4.2
Weather Version: 0.5

**Comment by mfrederickson** [comment]
Can you show me a screenshot of your weather content entry without including any confidential or private data?  I think that if there are four or more leading spaces in the template content then that will be treated as code (and thus rendered as-is) and not as html.

**Comment by shieldsit** [comment]
Do you mean as I'm setting up the location or after I've already searched and submitted it?

**Comment by mfrederickson** [comment]
Yes.
![image](https://user-images.githubusercontent.com/473165/30338364-e8a5c200-9797-11e7-9f5f-f576adc22ba4.png)

**Comment by shieldsit** [comment]
Here is that screen:

![concerto_winput](https://user-images.githubusercontent.com/4956108/30338436-b1fb8722-97b9-11e7-95b6-8c6e21d478ee.PNG)

**Comment by mfrederickson** [comment]
Very odd that it would change over night.  Was this after any kind of update on the server?

**Comment by shieldsit** [comment]
No, I was just about to post that nothing had changed that I'm aware of.  It was fine when leaving Friday and when I came in on Monday it was messed up.  I see a Passenger error in my Apache log if that matters?  

This is what it says:  
ERROR -- : **Airbrake: unexpected code (200). Body:  
stderr: env: /usr/bin/passenger-config: No such file or directory

**Comment by mfrederickson** [comment]
That probably needs to be another ticket.  Let me upgrade mine from 2.3.4 to 2.3.5 and see what happens.

**Comment by shieldsit** [comment]
OK.  I didn't think it was related but wanted to post it just in case.  I think it was producing that error before this started.

**Comment by mfrederickson** [comment]
Probably so.  Airbrake is used to log errors to an error catching server so app developers can monitor problems.  You can disable it by unchecking the setting "notify developers of errors" under the system settings.

**Comment by mfrederickson** [comment]
Aha.  I see the same thing on my end.  Let me publish the latest weather plugin and see it that resolves the problem.

**Comment by shieldsit** [comment]
I hate to say that makes me feel better, but misery loves company and all that!  If that fixes it can you tell me how to update?

**Comment by shieldsit** [comment]
And so apparently I was wrong when I said I didn't make any changes!  I must have updated Concerto to 2.3.5 and somehow thought the issue was there prior to the update.  Sorry about that!

**Comment by mfrederickson** [comment]
OK, I believe that I have fixed the problem-- the latest concerto-weather is actually 0.6 but it wasn't pushed with the concerto 2.3.5.  So if you update your concerto-weather plugin using the following method, your problem will be resolved.  However, once the gem is published, you should change back to the rubygems source for the gem so you are not pulling from the master branch of the repository.

Change your plugin source as follows:
![image](https://user-images.githubusercontent.com/473165/30340254-56629786-979e-11e7-9411-02b9b894f7ba.png)

Then restart your webserver:
`sudo service apache2 restart`

Then check your plugin version, and it should say 0.6:
![image](https://user-images.githubusercontent.com/473165/30340304-8cfe960a-979e-11e7-8ccd-e43840c546e8.png)

Then preview your screen and your weather should look correct.  Let me know.  Thanks.

**Comment by shieldsit** [comment]
Mine still says .5 after following your steps.

![cweather](https://user-images.githubusercontent.com/4956108/30340561-ea1fa028-97c0-11e7-8463-67a7c659e6f9.PNG)

**Comment by mfrederickson** [comment]
Mine did too until I restarted the webserver.  Did you do that?

**Comment by shieldsit** [comment]
Yeah, but I don't have git installed, that might help.  Installing it now.

**Comment by shieldsit** [comment]
hmm, you just restarted the service right?  Or do I need to reboot the machine?

**Comment by shieldsit** [comment]
Looks like I need to resubmit, I did one for daily high and low and it looks correct.  Thanks very very much for your assistance with this!

**Comment by mfrederickson** [comment]
I suspect the problem may still be there... I think it might recur when it refreshes the data from the weather site... I'm investigating...

**Comment by mfrederickson** [comment]
Hmmm... seems ok.  I guess I just had a bad entry cached...  If it recurs, please reopen this ticket.  Thanks.

**Comment by Kristof-VD-Ouweland** [comment]
Greetings,
I tried to follow the steps above, and the plugin is updated correctly, but I still see the HTML tags rather than the icons in the screens.
Any suggestions?
Thanks 
kristof

**Comment by mfrederickson** [comment]
Yes, you will need to remove or expire the prior weather content and then re-add under the new plugin.
