### ISSUE TITLE
Realtime weather works, forecasts don't display anything

### ISSUE THREAD

**Issue by mcisar** [concerto/concerto-weather#45]
using the concerto VM image, updated to concerto-weather 0.6 via git.   The realtime weather works just fine but if I try to set up either of the forecasts it just doesn't display anything.

If I look in the worker log  there is an invalid API key error popping up.   Looking carefully at the request it seems to be using  ...forecast/daily?...  which seems to be the 16 day forecast which requires a paid key.   I *think* that using   ...forecast?...  would use the 5 day forecast which works with the free key.  

I tried to test that theory and found the source file that contains the URI... but I've never touched ruby before so I've got ZERO clue on how I could compile that change to test :-)   Soooo... thats why I'm here.

Thanks

**Comment by mfrederickson** [comment]
@mcisar you are correct according to their site that is a paid service... They must have changed that...   my key must be grandfathered in because those forecasts work fine for me and I am not paying for it.  

Regardless, simply changing the api call won't resolve the problem because the results that come back differ, so we've got to make some more changes for it to work. I'll look into this...

**Comment by mcisar** [comment]
Thanks Marvin, much appreciated.

**Comment by mfrederickson** [comment]
https://openweathermap.org/forecast5#JSON

fyi This version of the forecast does not include a hi/low temp for each day.

**Comment by mcisar** [comment]
Well well, isn’t that sneaky 😊

I guess I may have to do some hacking to instead pull my weather and forecasts from the free feed provided by Environment Canada.

Cheers,
>>>>> Mike <<<<<

**Comment by mfrederickson** [comment]
Well, it does have the temp for every 3 hrs for a five day period, so you could obtain it that way.  You might want to try making the api call requesting an xml format and use the rss content type and format the results however you want, plucking various values, etc.  I'm sure if you posted it on stackoverflow someone would be able to help you determine the XSL template to use.

That's how I'd do it.  It's much more flexible that way.

**Comment by mfrederickson** [comment]
Well, that didn't work... but the XML results seem to have more info than the JSON results.
