### ISSUE TITLE
custom format string overwritten with interpolated values on build

### ISSUE THREAD

**Issue by chamblissb** [concerto/concerto-weather#47]
This is what I have for the Format String:

![concertoweatherformat](https://user-images.githubusercontent.com/37554424/37619235-c4d8f16e-2bb0-11e8-8a21-ff7c628b63bb.PNG)

But now I see this and it will change the temp or weather icon:

![concertoweather](https://user-images.githubusercontent.com/37554424/37619157-8631574e-2bb0-11e8-9ee4-f0b359a840d8.PNG)

**Comment by mfrederickson** [comment]
When you first add a piece of weather content it immediately loads the children.  Thereafter, if the background process is running [you can check this on the dashboard], it should refresh periodically (about every 5 minutes or so, or daily) throughout the display from-until period.

You can also purge the children and force them to repopulate (force update button).

**Comment by chamblissb** [comment]
It seems that no matter what I do, the weather will not update.  It always shows 44 degrees and windy. Even if a purge the children and force update.

Should I delete it and recreate it?

**Comment by mfrederickson** [comment]
I believe it is because your format string contains those literal values.  When I added some weather, I left the format string blank.

**Comment by mfrederickson** [comment]
Your topmost format string looks good, but what is in your screenshot looks like it contains static values.

**Comment by chamblissb** [comment]
The topmost format is what I put inside the Format String.  When I save it, the Format String changes to the current conditions and doesn't change.

**Comment by mfrederickson** [comment]
Might have been introduced here: https://github.com/concerto/concerto-weather/commit/b691ffe4372ef058dd7620defd43467d30e3612a#diff-2118ebeba41f4ec481c79746a95f8ce9.  Perhaps if we don't directly alter the format string...

**Comment by garci66** [comment]
I think I found the problem:

`       rawhtml = "\"" + format_string + "\""
       format_string.sub! '#{format_city}' format_city
       format_string.sub! '#{format_iconid}' format_iconid 
       format_string.sub! '#{format_icon}' format_icon
       format_string.sub! '#{format_high}' format_high
       format_string.sub! '#{format_low}' format_low
       format_string.sub! '#{format_current}' format_current`

all the format_string.sub should be rawhtml.sub, otherwise we're replacing the format string and not the actual html.

`       rawhtml = "\"" + format_string + "\""
       rawhtml .sub! '#{format_city}' format_city
       rawhtml .sub! '#{format_iconid}' format_iconid 
       rawhtml .sub! '#{format_icon}' format_icon
       rawhtml .sub! '#{format_high}' format_high
       rawhtml .sub! '#{format_low}' format_low
       rawhtml .sub! '#{format_current}' format_current
`

I don't have an easy way to commit the code now but I think that's the problem.

**Comment by garci66** [comment]
I think I found the culprit. Please look at the comment I just added on the
issue.

**Comment by mfrederickson** [comment]
I think the latest code is doing what you said...
https://github.com/concerto/concerto-weather/blob/master/app/models/weather.rb#L135

**Comment by garci66** [comment]
so now the question is which version is the system exhibiting the problem
using...

**Comment by mfrederickson** [comment]
It's in his original title for this issue, 0.6

**Comment by garci66** [comment]
Sorry. Im getting confused then. Not sure why would the template text be
updated instead of the child's html.

**Comment by mfrederickson** [comment]
This is probably why...
```
Loading development environment (Rails 5.1.5)
2.3.3 :001 > a = "hello there"
 => "hello there" 
2.3.3 :002 > b = a
 => "hello there" 
2.3.3 :003 > b.sub! "the", "cat"
 => "hello catre" 
2.3.3 :004 > a
 => "hello catre" 
2.3.3 :005 > 
```

**Comment by garci66** [comment]
Wow. That's new. Good catch. Thanks!!!
